import { Task } from './models/Task';

export const tasks: Task[] = [
  {
    id: 1,
    icon: 'star',
    title: 'Design Main Page',
    status: 'In Progress',
    progress: 60,
    dueDate: '2025-07-15',
    users: [101, 102],
    subtasks: [
      { id: 11, title: 'Subtask 1', status: 'Not Started' },
      { id: 12, title: 'Subtask 2', status: 'In Progress' },
      { id: 13, title: 'Subtask 3', status: 'Completed' },
    ],
  },
  {
    id: 2,
    icon: 'Plane',
    title: 'Setup DB',
    status: 'In Progress',
    progress: 39,
    dueDate: '2025-07-20',
    users: [103, 104],
  },
  {
    id: 3,
    icon: 'Plane',
    title: 'Build Auth API',
    status: 'Completed',
    progress: 100,
    dueDate: '2025-07-10',
    users: [105, 106],
  },
  {
    id: 4,
    icon: 'Plane',
    title: 'Test UI',
    status: 'In Progress',
    progress: 30,
    dueDate: '2025-07-18',
    users: [107, 108],
  },
  {
    id: 5,
    icon: 'Plane',
    title: 'Write Docs',
    status: 'Not Started',
    progress: 0,
    dueDate: '2025-07-25',
    users: [109],
  },
  {
    id: 6,
    icon: 'Plane',
    title: 'Optimize Server',
    status: 'In Progress',
    progress: 45,
    dueDate: '2025-07-22',
    users: [110, 111],
  },
  {
    id: 7,
    icon: 'Plane',
    title: 'Create Mobile App',
    status: 'Not Started',
    progress: 0,
    dueDate: '2025-08-01',
    users: [101, 112],
  },
  {
    id: 8,
    icon: 'Plane',
    title: 'Setup CI/CD',
    status: 'In Progress',
    progress: 80,
    dueDate: '2025-07-12',
    users: [113, 114],
  },
];
